### PR TITLE
Added support to not use Metis partitioner. Metis is now optional for…

### PR DESCRIPTION
**Pull request by neoblizz**
… gunrock. @sgpyc Can you please show me how to test, or test this yourself? I am not sure how to use `metis_partitioner.cuh` file to invoke the changes I have made. I tried `cmake` and compiling these changes and they work fine! It is suppose to print an error saying you cannot use metis partitioner if you do not have Metis installed. (Issue #97)

### CODE REVIEW

**Comment by neoblizz** [comment]
Also, fixed typos for `--partition-method` flag in all the test files.
Problem with metis partitioner is that I get the flag to enable or disable metis from CMakeLists.txt, but if the user only uses the `tests/bfs` and directly make there, the flag doesn't exist. Any ideas how I can fix that? @yzhwang is looking into `cmake` because we shouldn't have to change so many cmake files because our main file changed.

**Comment by yzhwang** [comment]
@neoblizz I think we should get rid of all the CMakeList.txt under each test/primitive_names directories. I figured when we run cmake once, it also adds Makefile to build_dir/tests/primitive_names (note, not gunrock/tests/ but build_dir you have chosen for all cmake generated files). Under those directories, you can actually run make to build each single primitive. I'm gonna have to talk to Andy and Yuduo whether it makes sense to get rid of all these cmakelist.txt since they are the ones who added them in the summer of 2014. But it seems that now we do have ways to build single primitive and we only need to keep one copy of cmakelist under the root directory.

**Comment by neoblizz** [comment]
@yzhwang Yes, I totally agree. Because making changes in the root `CMakeList.txt` doesn't translate into others, for example the issue I just solved with openmp support on OSX is currently only fixed for the root `CMakeList.txt`, to solve for rest it requires me to change in every single cmake file in the tests dir.

**Comment by sgpyc** [comment]
There is a master Makefile in tests, you can just change that

**Comment by neoblizz** [comment]
@sgpyc Yes, but we give people option to also use cmake using the CMakeLists.txt files, do we really need those?

**Comment by jowens** [comment]
Please make everything work with cmake. Not only is it cross-platform, it's got lots of helpful subroutines (like find openmp, etc.) that make it way easier to make anything complex work more easily.

**Comment by neoblizz** [comment]
I agree, that's how the case should be. I think @yzhwang and I were suggesting that the root CMakeList.txt should create the make files so they stay updated with whatever future changes we make.

**Comment by jowens** [comment]
I concur.

**Comment by sgpyc** [comment]
Does Cmake has the "include" feature? I think that's what may be useful.
And if you want to change or generate the Makefiles, it saves some work by doing it on the master Makefile, rather than AL the individual ones.

**Comment by yzhwang** [comment]
@neoblizz @sgpyc actually I was wrong about removing the CMakelist.txt under tests/primitive_name since they do get included here:
https://github.com/gunrock/gunrock/blob/master/CMakeLists.txt#L211
So now we are using add_subdirectory but since @neoblizz mentioned you have made some changes in the root CMakeLists.txt and they didn't propagate to individual CMakeLists.txt. I think you should make those as functions and put them in .cmake files so that they can be included in any CMakeLists.txt.
here is a post on the difference between add_subdirectory and include.
https://cmake.org/pipermail/cmake/2007-November/017897.html

Seems that we want to put the code that handles dependency issue in a .cmake file so that we can include in both the root CMakeLists.txt and several individual ones. Then, when we want to build only one primitive, we create a primitive_name_build dir, enter it and call:
cmake gunrock_dir/tests/primitive_name/
it will load the CMakeLists.txt under that primitive directory. Now when I do this, it complains several things since we probably don't have the correct CMakeLists.txt defined there. I will do some more experiments tonight.

**Comment by neoblizz** [comment]
I see, that makes sense. Separate the code in root CMakeLists.txt into individual modules that can be included in all CMakeLists.txt files. Question, the [Makefiles](https://github.com/gunrock/gunrock/blob/master/tests/bfs/Makefile) in the tests are generated through the CMakeLists.txt in the test? If not, then how will they get all the dependencies or do we even need them there once we have the CMakeLists.txt updated?

**Comment by yzhwang** [comment]
No, they are written by me before we used cmake. When we finished all the cmake updates, we can get rid of the individual makefiles under each primitive dir.

**Comment by sgpyc** [comment]
But they are useful for debugging purpose. Unless there is a good and easy way to know and change the actual make comment parameter by changing CMakeList.txt, I suggest to keep Makefile, and generate / change them by cmake

**Pull request merged**
