### PR TITLE
Add file IO support for comma-separated values file

### PR DESCRIPTION
**Pull request by yzhwang**
Can now use "csv" to read in edge lists of VIDs (with or without edge values).
Currently do not parse any comments in file head, only supported format is:
src_id, dst_id
or
src_id, dst_id, edge_value

VIDs will be mapped to continuous VertexID type ids. The mapping will be saved in a .vid-map file.
Add a test_csv.csv file for test in dataset/small.

### CODE REVIEW

**Comment by yzhwang** [comment]
@neoblizz Should I also add some tests to cover this? Suggestion?

**Comment by neoblizz** [comment]
This is good for now. Can we do the merge to gunrock:dev rather than master? And eventually bundle this into the next release?

The test csv file is good -- feel free to add a unit test for this.

**Comment by jowens** [comment]
@neoblizz actually meant "please add a unit test for this" :)

**Comment by yzhwang** [comment]
> This is good for now. Can we do the merge to gunrock:dev rather than master? And eventually bundle this into the next release?
> 
> The test csv file is good -- feel free to add a unit test for this.

Sounds good. Any suggestion on where to put unit tests? Do you put them in a separated folder or place them at the same folder with the implementation, but with a "_test" suffix? Just want to make sure my unit test aligns with the current way Gunrock handles tests.

**Comment by neoblizz** [comment]
> > This is good for now. Can we do the merge to gunrock:dev rather than master? And eventually bundle this into the next release?
> > The test csv file is good -- feel free to add a unit test for this.
> 
> Sounds good. Any suggestion on where to put unit tests? Do you put them in a separated folder or place them at the same folder with the implementation, but with a "_test" suffix? Just want to make sure my unit test aligns with the current way Gunrock handles tests.

Our unit tests are here: https://github.com/gunrock/gunrock/tree/master/unittests and also, some of the calls from those unit tests are made to this folder: https://github.com/gunrock/gunrock/tree/master/examples/core

Lots of examples there, hope this helps!

**Pull request merged**
