### PR TITLE
[docker] add README.md

### PR DESCRIPTION
**Pull request by bkj**
Adding docs for docker

### CODE REVIEW

**Comment by neoblizz** [comment]
I was saying for this PR, do we want this under gunrock/docs repo as well, as a page explaining the docker stuff?

**Comment by bkj** [comment]
Sure -- where exactly would it go?

I think it should be here as well -- good to have docs as close to the code as possible.

**Comment by neoblizz** [comment]
Yes, I agree. Keeping it here and merging this. It can go under `sources/includes` in the docs repo: https://github.com/gunrock/docs/tree/master/source/includes and then update the index.html.md's table to include that md file like there are others already included: https://github.com/gunrock/docs/blob/master/source/index.html.md

... merging.

**Comment by johari** [comment]
Hey!

Thank you for Docker instructions! Apart from small hiccups installing `nvidia-docker2` on my Ubuntu 18.04, I was able to run Gunrock tests inside my docker container. :)

**Pull request merged**
