### PR TITLE
Gunrock's Forking Workflow.

### PR DESCRIPTION
**Pull request by neoblizz**
Explanation of how we should structure gunrock's development using different forks and pull requests (this pull request being an example).

Sources: https://www.atlassian.com/git/tutorials/comparing-workflows#forking-workflow

### CODE REVIEW

**Comment by neoblizz** [comment]
Doc: https://github.com/neoblizz/gunrock/blob/master/doc/forking_workflow_gunrock.md

**Comment by ctcyang** [comment]
@sgpyc mentioned that one of the reasons we haven't been doing this is because it is time-consuming to manually run comprehensive test to check that the PR didn't break anything. What are some tools that people use to automate testing whenever someone submits a PR?

**Comment by neoblizz** [comment]
It is very common to use a bot to do that, and it can report results to slack. But yeah, having someone who is testing the code is also part of this (as an added check). @ctcyang idk if this is the answer, but I have seen projects use https://travis-ci.org/ and https://codecov.io/.

**Comment by yzhwang** [comment]
We can set up Jenkins too. https://github.com/jenkinsci/jenkins

**Comment by jowens** [comment]
So the big difference between the current workflow and this workflow is that development branches would no longer be branches but instead be forks. Accurate? What's the advantage here? I do like the ability to look at a pull request and comment on it.

I think CI would be awesome. Not clear to me if we can use a cloud service (in which case I don't know which has GPU support, but I know NVIDIA is working on it) or if we need to set up something locally (in which case I'd be happy to ask COE if they'd set one up). Thoughts?

**Comment by neoblizz** [comment]
Yes, that is accurate. Having things in forks and then having the pull requests for the changes encourages code review, or at the very least some automated testing and instant feedback on those using things like Jenkins or Travis CI. In the end, this also simplifies how we push out a release, instead of merging tons of branches we only have to test one dev branch, because that's where all the changes will go to now (less work for whoever is doing the cleanup before the release).

I read somewhere that Travis CI was interested in supporting GPUs for CUDA. I'll have to check up on that again, but if their Cloud service doesn't work for us, we can host one even on mario or COE as you suggested.

**Comment by neoblizz** [comment]
Should I start setting up Jenkins? @jowens Should we go ahead with this approach or are there any other obstructions/questions?

**Comment by jowens** [comment]
I sent a query to COE staff, no reply yet.

First, do we want Jenkins or Travis CI? 

I think it's probably most sensible to start with picking a CI system (Jenkins or Travis CI) then next writing a test before we set up the CI system. I don't want to see you make the effort to set up a CI system then we find something outside the group we can use instead. But I know we need to write tests.

**Comment by neoblizz** [comment]
I am working on setting up gtest with a sample test, but Jenkins or Travis CI can take one of our current gunrock apps tests written already.

**Comment by jowens** [comment]
Also, transition plan? We have several long-lived branches. Be specific about how we transition. Presumably branch owner checks in, has no more branches, then does further development with new plan?

**Comment by neoblizz** [comment]
I am creating an issue per branch and assigning it to the branch owner. I would request for them to either create a new fork or update their personal fork so that they have all the branches existing on their fork before the branch is removed. This way, all they have to do is create a pull request from their feature branch to the dev branch once it is time to merge.

**Pull request merged**
