### PR TITLE
Support OpenMP auto build on Mac OS X with GPU

### LINKED ISSUE #314: Support OpenMP on Mac OS X with GPU
https://github.com/gunrock/gunrock/blob/40b65bd6239c6d74bc012cb6669c7f230f0c61a6/cmake/FindOpenMP.cmake#L21

```bash
/opt/local/lib /opt/local/lib/libomp
```

The hard code is too weak.

You guys can use `ExternalProject_Add` to support OpenMP on MacOS X (https://cmake.org/cmake/help/v3.0/module/ExternalProject.html) where can build OpenMP (https://github.com/llvm-mirror/openmp) as an external project.

### PR DESCRIPTION
**Pull request by gangliao**
Fix #314

```
gangl@GangLiao ~/G/g/g/build> cmake -DGUNROCK_GENCODE_SM30=ON -DGUNROCK_GENCODE_SM50=ON ..
-- The C compiler identification is AppleClang 8.0.0.8000038
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- Check for working C compiler: /Applications/Xcode8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "7.5")
-- Boost version: 1.61.0
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
-- Found OpenMP (-libomp)
-- Found Metis
-- Project Added: bc
-- Project Added: bfs
-- Project Added: cc
-- Project Added: pr
-- Project Added: sssp
-- Project Added: hits
-- Project Added: salsa
-- Project Added: wtf
-- Project Added: topk
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/liaogang/Google Drive/github/gunrock/build


gangl@GangLiao ~/G/g/g/build> make -j12
Scanning dependencies of target extern_openmp
[  0%] Creating directories for 'extern_openmp'
[  1%] Performing download step (git clone) for 'extern_openmp'
Cloning into 'extern_openmp'...
Note: checking out '1d9902d5b99ee93e0bb3f886e08414a81f21cd2a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 1d9902d... [OMPT] Omissionin in OMPT Formatting
[  3%] No update step for 'extern_openmp'
[  3%] No patch step for 'extern_openmp'
[  4%] Performing configure step for 'extern_openmp'
-- extern_openmp configure command succeeded.  See also /Users/liaogang/Google Drive/github/gunrock/build/omp/src/extern_openmp-stamp/extern_openmp-configure-*.log
[  5%] Performing build step for 'extern_openmp'
Scanning dependencies of target libomp-needed-headers
[  5%] Generating kmp_i18n_default.inc
[  5%] Generating kmp_i18n_id.inc
[  5%] Built target libomp-needed-headers
Scanning dependencies of target omp
[  8%] Building C object runtime/src/CMakeFiles/omp.dir/thirdparty/ittnotify/ittnotify_static.c.o
[ 13%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_atomic.cpp.o
[ 16%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_csupport.cpp.o
[ 16%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_alloc.cpp.o
[ 22%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_itt.cpp.o
[ 22%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_debug.cpp.o
[ 25%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_environment.cpp.o
[ 27%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_error.cpp.o
[ 30%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_i18n.cpp.o
[ 33%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_global.cpp.o
[ 36%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_io.cpp.o
[ 38%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_runtime.cpp.o
[ 41%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_settings.cpp.o
[ 44%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_str.cpp.o
[ 47%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_tasking.cpp.o
[ 50%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_taskq.cpp.o
[ 52%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_threadprivate.cpp.o
[ 55%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_utility.cpp.o
[ 58%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_barrier.cpp.o
[ 61%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_wait_release.cpp.o
[ 63%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_affinity.cpp.o
[ 66%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_dispatch.cpp.o
[ 69%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_lock.cpp.o
[ 72%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_sched.cpp.o
[ 75%] Building CXX object runtime/src/CMakeFiles/omp.dir/z_Linux_util.cpp.o
[ 77%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o
[ 80%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_taskdeps.cpp.o
[ 83%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_cancel.cpp.o
[ 86%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_ftn_cdecl.cpp.o
[ 88%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_ftn_extra.cpp.o
[ 91%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_version.cpp.o
[ 94%] Building CXX object runtime/src/CMakeFiles/omp.dir/ompt-general.cpp.o
[ 97%] Building C object runtime/src/CMakeFiles/omp.dir/z_Linux_asm.S.o
[100%] Linking C shared library libomp.dylib
[100%] Built target omp
[  6%] Performing install step for 'extern_openmp'
[  5%] Built target libomp-needed-headers
[100%] Built target omp
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/liaogang/Google Drive/github/gunrock/build/install/omp/lib/libomp.dylib
-- Installing: /Users/liaogang/Google Drive/github/gunrock/build/install/omp/include/omp.h
-- Installing: /Users/liaogang/Google Drive/github/gunrock/build/install/omp/include/ompt.h
[  7%] Completed 'extern_openmp'
[  7%] Built target extern_openmp
[  9%] Building NVCC (Device) object tests/bc/CMakeFiles/bc.dir/__/__/externals/moderngpu/src/bc_generated_mgpucontext.cu.o
[  9%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/gunrock_generated_mgpucontext.cu.o
[ 10%] Building NVCC (Device) object tests/bfs/CMakeFiles/bfs.dir/__/__/externals/moderngpu/src/bfs_generated_mgpucontext.cu.o
[ 11%] Building NVCC (Device) object tests/cc/CMakeFiles/cc.dir/__/__/externals/moderngpu/src/cc_generated_mgpucontext.cu.o
[ 12%] Building NVCC (Device) object tests/bfs/CMakeFiles/bfs.dir/bfs_generated_test_bfs.cu.o
[ 13%] Building NVCC (Device) object tests/sssp/CMakeFiles/sssp.dir/__/__/externals/moderngpu/src/sssp_generated_mgpucontext.cu.o
[ 13%] Building NVCC (Device) object tests/bc/CMakeFiles/bc.dir/bc_generated_test_bc.cu.o
[ 14%] Building NVCC (Device) object tests/hits/CMakeFiles/hits.dir/__/__/externals/moderngpu/src/hits_generated_mgpucontext.cu.o
[ 16%] Building NVCC (Device) object tests/salsa/CMakeFiles/salsa.dir/__/__/externals/moderngpu/src/salsa_generated_mgpucontext.cu.o
[ 16%] Building NVCC (Device) object tests/pr/CMakeFiles/pr.dir/__/__/externals/moderngpu/src/pr_generated_mgpucontext.cu.o
[ 17%] Building NVCC (Device) object tests/wtf/CMakeFiles/wtf.dir/__/__/externals/moderngpu/src/wtf_generated_mgpucontext.cu.o
[ 18%] Building NVCC (Device) object tests/topk/CMakeFiles/topk.dir/__/__/externals/moderngpu/src/topk_generated_mgpucontext.cu.o
[ 19%] Building NVCC (Device) object tests/sssp/CMakeFiles/sssp.dir/sssp_generated_test_sssp.cu.o
[ 20%] Building NVCC (Device) object tests/cc/CMakeFiles/cc.dir/cc_generated_test_cc.cu.o
[ 21%] Building NVCC (Device) object tests/salsa/CMakeFiles/salsa.dir/salsa_generated_test_salsa.cu.o
[ 22%] Building NVCC (Device) object tests/wtf/CMakeFiles/wtf.dir/wtf_generated_test_wtf.cu.o
[ 22%] Building NVCC (Device) object tests/pr/CMakeFiles/pr.dir/pr_generated_test_pr.cu.o
[ 23%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/bfs/gunrock_generated_bfs_app.cu.o
[ 24%] Building NVCC (Device) object tests/topk/CMakeFiles/topk.dir/topk_generated_test_topk.cu.o
[ 25%] Building NVCC (Device) object tests/bc/CMakeFiles/bc.dir/__/__/gunrock/util/bc_generated_test_utils.cu.o
[ 26%] Building NVCC (Device) object tests/cc/CMakeFiles/cc.dir/__/__/gunrock/util/cc_generated_test_utils.cu.o
[ 27%] Building NVCC (Device) object tests/hits/CMakeFiles/hits.dir/hits_generated_test_hits.cu.o
[ 28%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/bc/gunrock_generated_bc_app.cu.o
[ 29%] Building NVCC (Device) object tests/topk/CMakeFiles/topk.dir/__/__/gunrock/util/topk_generated_test_utils.cu.o
[ 30%] Building NVCC (Device) object tests/wtf/CMakeFiles/wtf.dir/__/__/gunrock/util/wtf_generated_test_utils.cu.o
[ 31%] Building NVCC (Device) object tests/salsa/CMakeFiles/salsa.dir/__/__/gunrock/util/salsa_generated_test_utils.cu.o
[ 32%] Building NVCC (Device) object tests/wtf/CMakeFiles/wtf.dir/__/__/gunrock/util/wtf_generated_error_utils.cu.o
[ 33%] Building NVCC (Device) object tests/sssp/CMakeFiles/sssp.dir/__/__/gunrock/util/sssp_generated_test_utils.cu.o

```

### CODE REVIEW

**Comment by gangliao** [comment]
```bash
[ 22%] Built target salsa
[ 22%] Built target pr
[ 31%] Built target hits
[ 39%] Built target bfs
[ 46%] Built target topk
[ 54%] Built target wtf
[ 62%] Built target sssp
[ 70%] Built target cc
[ 77%] Built target bc
[ 89%] Built target gunrock
[ 91%] Built target shared_lib_example
[ 94%] Built target shared_lib_cc
[ 97%] Built target shared_lib_bfs
[ 97%] Built target shared_lib_pr
[ 99%] Built target shared_lib_sssp
[100%] Built target shared_lib_bc
```

**Comment by gangliao** [comment]
```bash
gangl@GangLiao ~/G/g/g/build> ctest -j12
Test project /Users/liaogang/Google Drive/github/gunrock/build
      Start  1: TEST_BFS
      Start  2: TEST_BC
      Start  3: TEST_CC
      Start  4: TEST_SSSP
      Start  5: TEST_PAGERANK
      Start  6: TEST_TOPK
      Start  7: SHARED_LIB_TEST_BFS
      Start  8: SHARED_LIB_TEST_BC
      Start  9: SHARED_LIB_TEST_CC
      Start 10: SHARED_LIB_TEST_SSSP
      Start 11: SHARED_LIB_TEST_PAGERANK
 1/11 Test  #6: TEST_TOPK ........................   Passed    1.86 sec
 2/11 Test  #8: SHARED_LIB_TEST_BC ...............   Passed    1.96 sec
 3/11 Test  #4: TEST_SSSP ........................   Passed    2.01 sec
 4/11 Test  #5: TEST_PAGERANK ....................   Passed    2.04 sec
 5/11 Test  #1: TEST_BFS .........................   Passed    2.12 sec
 6/11 Test  #2: TEST_BC ..........................   Passed    2.12 sec
 7/11 Test  #3: TEST_CC ..........................   Passed    2.12 sec
 8/11 Test  #7: SHARED_LIB_TEST_BFS ..............   Passed    2.11 sec
 9/11 Test  #9: SHARED_LIB_TEST_CC ...............   Passed    2.11 sec
10/11 Test #10: SHARED_LIB_TEST_SSSP .............   Passed    2.11 sec
11/11 Test #11: SHARED_LIB_TEST_PAGERANK .........   Passed    2.11 sec

100% tests passed, 0 tests failed out of 11

Total Test time (real) =   2.12 sec
```

**Comment by neoblizz** [comment]
👍 I'll let this test to see if it would break anything else, but the changes look great! Thank you for adding mac support!

**Comment by gangliao** [comment]
@neoblizz  cool!

**Pull request merged**
