### PR TITLE
Prevent duplication of key "load-time" in output json

### PR DESCRIPTION
**Pull request by achalagarwal**
@crozhon  I still haven't figured out where the second ```setVal()``` for **load-time** is being called, but commenting out this one works!

### CODE REVIEW

**Comment by crozhon** [comment]
Could you just delete it instead of commenting it out? We can always find it via git history if needed. Then I'll accept this.

**Comment by achalagarwal** [comment]
Done!

Also, I can't link this pull request to the issue, do I need to be a collaborator to do that? @jowens can you add me?

**Comment by jowens** [comment]
Done.

**Comment by achalagarwal** [comment]
> Done.

Thanks!

But still can't link it to the issue :thinking:

**Pull request merged**
