### PR TITLE
Improved support for Finding OpenMP on OSX & Updated version for CUDA & Boost.

### PR DESCRIPTION
**Pull request by neoblizz**
Issue: #99 @jowens Can you please try this `cmake` on OSX and see if the OpenMP gets detected properly? I will clean it up if it works and submit a new commit.

### CODE REVIEW

**Comment by jowens** [comment]
Hm. First, it doesn't appear to find what it needs to find:

```
mission-burrito 9954$ make
-- Found CUDA: /Developer/NVIDIA/CUDA-7.5 (found suitable version "7.5", minimum required is "7.5")
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
CMake Warning at CMakeLists.txt:57 (message):
  Clang detected: OpenMP (libomp) was requested but support was not found


-- Found Metis
-- Found CUDA: /Developer/NVIDIA/CUDA-7.5 (found version "7.5")
-- Configuring done
```

**Comment by jowens** [comment]
Second, it doesn't find omp.h any more:

```
[  1%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/bfs/gunrock_generated_bfs_app.cu.o
In file included from /Users/jowens/Documents/working/gunrock/gunrock/app/bfs/bfs_app.cu:17:
In file included from /Users/jowens/Documents/working/gunrock/gunrock/graphio/market.cuh:23:
/Users/jowens/Documents/working/gunrock/gunrock/graphio/utils.cuh:39:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
```

That header file is in `/opt/local/include/libomp/` . I'm presuming it'll have to link also (`/opt/local/lib/libomp`).

**Comment by neoblizz** [comment]
@jowens Can you please try this and tell me the output? Last commit took care of repeated OpenMP check for mac without having to `QUIET` it, this one has proper includes for the Macports.

**Comment by jowens** [comment]
Also cranky, sorry to say.

```
CMake Warning at CMakeLists.txt:57 (message):
  Clang detected - CMake Root: /opt/local/lib;/opt/local/include


CMake Warning at CMakeLists.txt:70 (message):
  Clang detected: OpenMP (libomp) /opt/local/lib;/opt/local/include was
  requested but support was not found
```

```
[  1%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/bfs/gunrock_generated_bfs_app.cu.o
In file included from /Users/jowens/Documents/working/gunrock/gunrock/app/bfs/bfs_app.cu:17:
In file included from /Users/jowens/Documents/working/gunrock/gunrock/graphio/market.cuh:23:
/Users/jowens/Documents/working/gunrock/gunrock/graphio/utils.cuh:39:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
CMake Error at gunrock_generated_bfs_app.cu.o.cmake:203 (message):
  Error generating
  /Users/jowens/Documents/working/gunrock-build/gunrock/CMakeFiles/gunrock.dir/app/bfs/./gunrock_generated_bfs_app.cu.o
```

**Comment by neoblizz** [comment]
@jowens, thank you for testing, can you please tell me what files you have in `/opt/local/lib/libomp` or `/opt/local/include/libomp`? It is either the extra path I have to add or I don't have the library name correct, sorry for asking for so many tests, hopefully next one will be the last!

**Comment by jowens** [comment]
```
$ ls /opt/local/lib/libomp
libgomp.dylib  libiomp5.dylib  libomp.dylib
$ ls /opt/local/include/libomp
omp.h
$ port notes libomp
libomp has the following notes:
  Use with clang-3.[78] (when built with +openmp variant) by adding
  "-fopenmp" to your compile and link lines.
  (Or "-I/opt/local/include/libomp -L/opt/local/lib/libomp -fopenmp"
  if clang is installed without +openmp.)
$
```

**Comment by neoblizz** [comment]
Added `FIND_PATH` and `FIND_LIBRARY` now it explicitly checks for `libomp` or similar names in the following directories:

```
set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} 	 /opt/local/lib /opt/local/lib/libomp)
set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} 	 /opt/local/include /opt/local/include/libomp)
```

**Comment by jowens** [comment]
This appears to work. It's got some problems with random that weren't there before, so I'm not 100% sure, but I think it's correct. However, it would be nice if it gave a "found" message that indicated it found MacPorts's libomp, e.g.:

```
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found CUDA: /Developer/NVIDIA/CUDA-7.5 (found suitable version "7.5", minimum required is "6.5")
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
-- Found Metis
-- Found CUDA: /Developer/NVIDIA/CUDA-7.5 (found version "7.5")
-- Configuring done
```

**Comment by neoblizz** [comment]
Awesome! I will clean it up, I have to change the `CUDA` version back to `7.5`, as we now require it. What problems showed up with this? The pthread.h thing?

```
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
```

**Comment by jowens** [comment]
These messages aren't problems at all, but they do indicate what configure is doing. It's also configuring OpenMP and should print a message accordingly ("using libomp from Macports", for instance).

**Comment by neoblizz** [comment]
Cleaned up the file, added status message `message(STATUS "Found OpenMP (-libomp)")` when `libomp` is found. Boost is now updated to `1.58` and CUDA updated to `7.5`.

**Comment by jowens** [comment]
`-- Found OpenMP (-libomp)`

Woo!

**Pull request merged**
