### PR TITLE
Create app template header for subgraph matching

### PR DESCRIPTION
**Pull request by Laurawly**
@aschaffer Does this pr illustrate your suggestions? @neoblizz Could you review? If this is the way to separate template functions to a header file, I'll update bc as well.

### CODE REVIEW

**Comment by aschaffer** [comment]
Not really, no. `sm_app.cuh` should contain *full* template definitions (not just declarations);
Then `sm_app.cu` should include `sm_app.cuh` and provide the full definition of `UseParameters(...)` function;
Finally an `sm(...)` function should be exposed in `gunrock.h`, similar to how `bc(...)` is exposed.

**Comment by jowens** [comment]
Thank you @aschaffer!

**Comment by Laurawly** [comment]
> Not really, no. `sm_app.cuh` should contain _full_ template definitions (not just declarations);
> Then `sm_app.cu` should include `sm_app.cuh` and provide the full definition of `UseParameters(...)` function;
> Finally an `sm(...)` function should be exposed in `gunrock.h`, similar to how `bc(...)` is exposed.

I see what you mean. So for the `sm(...)` function exposed like `bc(...)` in `gunrock.h`, does this pr https://github.com/gunrock/gunrock/pull/591 do the job?

**Comment by aschaffer** [comment]
Also, this issue of having template functions defined in implementation files(`*.cu`) along with non-template function `UseParameters(...)` seems to happen in 21 files:

./bc/bc_app.cu,
./bfs/bfs_app.cu,
./color/color_app.cu,
./geo/geo_app.cu,
./gtc/gtc_app.cu,
./gtf/gtf_app.cu,
./hello/hello_app.cu,
./hits/hits_app.cu,
./knn/knn_app.cu,
./louvain/louvain_app.cu,
./mf/mf_app.cu,
./pr/pr_app.cu,
./proj/proj_app.cu,
./pr_nibble/pr_nibble_app.cu,
./rw/rw_app.cu,
./sage/sage_app.cu,
./sm/sm_app.cu,
./ss/ss_app.cu,
./sssp/sssp_app.cu,
./tc/tc_app.cu,
./vn/vn_app.cu,

Although most of them are also exposed through `gunrock.h` (for example, `bc(...)`). So, to avoid linker issues with these it would be helpful to do same thing fro them, too: separate function template definitions in headers (`*_app.cuh`), away from non-template function definitions, which should reside in implementation files (`*_app.cu`).

**Comment by aschaffer** [comment]
> 
> 
> > Not really, no. `sm_app.cuh` should contain _full_ template definitions (not just declarations);
> > Then `sm_app.cu` should include `sm_app.cuh` and provide the full definition of `UseParameters(...)` function;
> > Finally an `sm(...)` function should be exposed in `gunrock.h`, similar to how `bc(...)` is exposed.
> 
> I see what you mean. So for the `sm(...)` function exposed like `bc(...)` in `gunrock.h`, does this pr #591 do the job?

No, because it looks like the template functions are still _defined_ in the `*_app.cu` file (unless I'm missing something). Again, templates need to be fully defined in header files (`*_app.cuh`).

**Comment by Laurawly** [comment]
> > > Not really, no. `sm_app.cuh` should contain _full_ template definitions (not just declarations);
> > > Then `sm_app.cu` should include `sm_app.cuh` and provide the full definition of `UseParameters(...)` function;
> > > Finally an `sm(...)` function should be exposed in `gunrock.h`, similar to how `bc(...)` is exposed.
> > 
> > 
> > I see what you mean. So for the `sm(...)` function exposed like `bc(...)` in `gunrock.h`, does this pr #591 do the job?
> 
> No, because it looks like the template functions are still _defined_ in the `*_app.cu` file (unless I'm missing something). Again, templates need to be fully defined in header files (`*_app.cuh`).

Trying to understand better here, @aschaffer In https://github.com/gunrock/gunrock/blob/dev/gunrock/app/bc/bc_app.cu#L260, bc has template as well, does "expose `sm(...)` like `bc(...)`" mean something else?

**Comment by aschaffer** [comment]
> 
> 
> > > > Not really, no. `sm_app.cuh` should contain _full_ template definitions (not just declarations);
> > > > Then `sm_app.cu` should include `sm_app.cuh` and provide the full definition of `UseParameters(...)` function;
> > > > Finally an `sm(...)` function should be exposed in `gunrock.h`, similar to how `bc(...)` is exposed.
> > > 
> > > 
> > > I see what you mean. So for the `sm(...)` function exposed like `bc(...)` in `gunrock.h`, does this pr #591 do the job?
> > 
> > 
> > No, because it looks like the template functions are still _defined_ in the `*_app.cu` file (unless I'm missing something). Again, templates need to be fully defined in header files (`*_app.cuh`).
> 
> Trying to understand better here, @aschaffer In https://github.com/gunrock/gunrock/blob/dev/gunrock/app/bc/bc_app.cu#L260, bc has template as well, does "expose `sm(...)` like `bc(...)`" mean something else?

I'm saying a C-style API must be exposed in `gunrock.h` for `sm(...)` as it is for `bc(...)`. That's one issue. Another issue is that headers are defined in implementation files, `*_app.cu` and they should _NOT_ be. Neither for `sm` nor for `bc` and nor for the other 19 files enumerated above.

Look, to clarify again, a correct template-inclusion model works like this:
Say you have a template function foo that you call somewhere and want to expose an API for it. Then the way to do it is:

//header
//foo.hpp:
template<typename T>
void foo(T t)
{
   //definition here...
}

//implementation file
//foo.cpp:
#include "foo.hpp"
void bar(int i)
{
   foo(i);
} 

//other non-template functions:
int func1(std::string& s)
{
  //code here...
}
//etc.

//...and then expose template<typename T> foo to a C-style API:
void foo_api_i(int i)
{
   foo(i);
}

void foo_api_d(double d)
{
    foo(d);
}
//...more if necessary

//then finally provide a C-style header (like `gunrock.h`) to expose the API implementations
//c_api.h:
void foo_api_i(int d);
void foo_api_d(double d);

**Comment by aschaffer** [comment]
BTW, there's another issue (not sure where to post it, I've already sent an email about it), so I'll re-post it here, although I think a fix might be already in progress:

I’m trying to build cugraph w/ latest Gunrock dependencies (`v1.0`) but I get this error:
```
bld_gunrock_latest/gunrock/gunrock/graphio/grmat.cuh:17:42: fatal error: gunrock/util/memset_kernel.cuh: No such file or directory
compilation terminated.
```
This file, ` memset_kernel.cuh` is included by `grmat.cuh`, but it doesn’t exist, actually. However, gunrock build succeeded.

**Comment by Laurawly** [comment]
> BTW, there's another issue (not sure where to post it, I've already sent an email about it), so I'll re-post it here, although I think a fix might be already in progress:
> 
> I’m trying to build cugraph w/ latest Gunrock dependencies (`v1.0`) but I get this error:
> 
> ```
> bld_gunrock_latest/gunrock/gunrock/graphio/grmat.cuh:17:42: fatal error: gunrock/util/memset_kernel.cuh: No such file or directory
> compilation terminated.
> ```
> 
> This file, ` memset_kernel.cuh` is included by `grmat.cuh`, but it doesn’t exist, actually. However, gunrock build succeeded.

You are welcome to create a new issue for it in https://github.com/gunrock/gunrock/issues.

**Comment by Laurawly** [comment]
@aschaffer Could you take another look at the updated PR?

**Comment by neoblizz** [comment]
> BTW, there's another issue (not sure where to post it, I've already sent an email about it), so I'll re-post it here, although I think a fix might be already in progress:
> 
> I’m trying to build cugraph w/ latest Gunrock dependencies (`v1.0`) but I get this error:
> 
> ```
> bld_gunrock_latest/gunrock/gunrock/graphio/grmat.cuh:17:42: fatal error: gunrock/util/memset_kernel.cuh: No such file or directory
> compilation terminated.
> ```
> 
> This file, ` memset_kernel.cuh` is included by `grmat.cuh`, but it doesn’t exist, actually. However, gunrock build succeeded.

My reply addressing this in the email (just to keep a record of it in github):
> Hi Andrei, good catch! grmat is actually an application that is not ported to v1.0.0, so I excluded it from the build files, which is why we don't get any error when building gunrock. But it shouldn't have been included in the master branch and should only exist in dev until it is properly ported.

**Comment by aschaffer** [comment]
> 
> > Hi Andrei, good catch! grmat is actually an application that is not ported to v1.0.0, so I excluded it from the build files, which is why we don't get any error when building gunrock. But it shouldn't have been included in the master branch and should only exist in dev until it is properly ported.

Hmm, lack of `grmat` support might be a problem for us, because we do do provide it (via older version of gunrock). I'm not sure what's the best course of action here.

**Comment by aschaffer** [comment]
> 
> 
> @aschaffer Could you take another look at the updated PR?

Will do, as soon as I get a window. I'm in a meeting now.

**Comment by aschaffer** [comment]
Also, another issue: HITS. It doesn't seem exposed in `gunrock.h` (maybe I'm wrong). Is that work in progress?

**Comment by Laurawly** [comment]
@aschaffer Do you mean this line? https://github.com/Laurawly/gunrock/blob/eeac0137d14bb73dfb9262ea530a4eede9e1af1c/gunrock/gunrock.h#L400

**Comment by aschaffer** [comment]
> 
> 
> > @aschaffer Could you take another look at the updated PR?
> 
> Will do, as soon as I get a window. I'm in a meeting now.

That looks better, but you still need to expose at least one `sm(...)` declaration in `gunrock.h`; (potentially more than one, for different combinations of template arguments of the underlying call to the `template<...> sm(...)` function). And then, that `sm(...)` API declaration in `gunrock.h` must have an implementation (definition) somewhere. Look at how BC is done in `bc_app.cu`:

```
double bc(const int num_nodes, const int num_edges, const int *row_offsets,
          const int *col_indices, int source, float *bc_values, float *sigmas,
          int *labels) {
  return bc(num_nodes, num_edges, row_offsets, col_indices, 1 /* num_runs */,
            &source, &bc_values, &sigmas, &labels);
}
```
The API `bc(...)` (non-template) calls the template and then its prototype is exposed in `gunrock.h`. You need to do the same for SM. (except leave the templates in `sm_app.cuh`; this needs to be fixed in BC as well, eventually, but could be done in a later PR).

**Comment by aschaffer** [comment]
> 
> 
> @aschaffer Do you mean this line? https://github.com/Laurawly/gunrock/blob/eeac0137d14bb73dfb9262ea530a4eede9e1af1c/gunrock/gunrock.h#L400

I didn't see this file in the chengelist. In fact I can only see 2 files changed w/ this PR: `sm_app.cu` and `sm_app.cuh`. But anyway: yes, that prototype in `gunrock.h` is necessary. But where is the implementation?

**Comment by Laurawly** [comment]
@aschaffer If you pull the latest gunrock::dev, you could see it. It's merged this morning. Commit dc6cddcdb212aae43075f1e49f624e49f0e7127c

**Comment by aschaffer** [comment]
> 
> 
> @aschaffer If you pull the latest gunrock::dev, you could see it. It's merged this morning. Commit [dc6cddc](https://github.com/gunrock/gunrock/commit/dc6cddcdb212aae43075f1e49f624e49f0e7127c)

OK. But where is the `sm(...)` _non-template_ implementation? You need that in `sm_app.cu`, same as you have `bc(...)` in `bc_app.cu`. *And*, same as non-template `bc(...)` calls the `template<...> bc(...)`, in `bc_app.cu` you also need the non-template `sm(...)` call the `template<...> sm(...)` in `sm_app.cu`.

**Comment by neoblizz** [comment]
> > @aschaffer If you pull the latest gunrock::dev, you could see it. It's merged this morning. Commit [dc6cddc](https://github.com/gunrock/gunrock/commit/dc6cddcdb212aae43075f1e49f624e49f0e7127c)
> 
> OK. But where is the `sm(...)` _non-template_ implementation? You need that in `sm_app.cu`, same as you have `bc(...)` in `bc_app.cu`. _And_, same as non-template `bc(...)` calls the `template<...> bc(...)`, in `bc_app.cu` you also need the non-template `sm(...)` call the `template<...> sm(...)` in `sm_app.cu`.

Isn't this what you are talking about?
https://github.com/gunrock/gunrock/blob/dc6cddcdb212aae43075f1e49f624e49f0e7127c/gunrock/app/sm/sm_app.cu#L251-L273

**Comment by neoblizz** [comment]
> Also, another issue: HITS. It doesn't seem exposed in `gunrock.h` (maybe I'm wrong). Is that work in progress?

@jdwapman can you please work on exposing this in `gunrock.h`?

**Comment by neoblizz** [comment]
> Hmm, lack of `grmat` support might be a problem for us, because we do do provide it (via older version of gunrock). I'm not sure what's the best course of action here.

Ideally, everything from v0.5.x will be ported to the v1.x.x API, it is just the engineering effort needed to get there. For grmat, it is relatively simple application, the memset stuff can just be removed. @jowens can comment on the priority of things being ported.

**Comment by aschaffer** [comment]
> 
> 
> > > @aschaffer If you pull the latest gunrock::dev, you could see it. It's merged this morning. Commit [dc6cddc](https://github.com/gunrock/gunrock/commit/dc6cddcdb212aae43075f1e49f624e49f0e7127c)
> > 
> > 
> > OK. But where is the `sm(...)` _non-template_ implementation? You need that in `sm_app.cu`, same as you have `bc(...)` in `bc_app.cu`. _And_, same as non-template `bc(...)` calls the `template<...> bc(...)`, in `bc_app.cu` you also need the non-template `sm(...)` call the `template<...> sm(...)` in `sm_app.cu`.
> 
> Isn't this what you are talking about?
> 
> https://github.com/gunrock/gunrock/blob/dc6cddcdb212aae43075f1e49f624e49f0e7127c/gunrock/app/sm/sm_app.cu#L251-L273

OK, I'm confused now: I don't see that function defined in `sm_app.cu` of this PR; also, in the snippet above I do see template definitions, which I thought have been moved out (as they should) in `sm_app.cuh`.

**Comment by jowens** [comment]
There's no research value in porting some of the old code; it's strictly a question of resources to do engineering work; we've got a lot of important future-Gunrock research projects to undertake that I think will make more of a difference in Gunrock's future, as well as a bunch of engineering effort. Trying to balance all of these things, and wanting to make @aschaffer and his team happy at the same time. A good first project for a new student if someone joins the software team in the fall.

**Comment by Laurawly** [comment]
@aschaffer It'll be clearer if you view files this way: https://github.com/gunrock/gunrock/blob/9ba37e7a2a77a3bf1c8cef316994cf5aad4fce48/gunrock/app/sm/sm_app.cu

**Comment by aschaffer** [comment]
> 
> 
> @aschaffer It'll be clearer if you view files this way: https://github.com/gunrock/gunrock/blob/9ba37e7a2a77a3bf1c8cef316994cf5aad4fce48/gunrock/app/sm/sm_app.cu
> 
Yes, that's correct.

**Comment by aschaffer** [comment]
Now, this process (with the templates in headers) must (eventually, maybe not this PR, but the sooner the better) be replicated for the remaining `*_app.cu` files:

./bc/bc_app.cu,
./bfs/bfs_app.cu,
./color/color_app.cu,
./geo/geo_app.cu,
./gtc/gtc_app.cu,
./gtf/gtf_app.cu,
./hello/hello_app.cu,
./hits/hits_app.cu,
./knn/knn_app.cu,
./louvain/louvain_app.cu,
./mf/mf_app.cu,
./pr/pr_app.cu,
./proj/proj_app.cu,
./pr_nibble/pr_nibble_app.cu,
./rw/rw_app.cu,
./sage/sage_app.cu,
~./sm/sm_app.cu,~
./ss/ss_app.cu,
./sssp/sssp_app.cu,
./tc/tc_app.cu,
./vn/vn_app.cu,

**Comment by Laurawly** [comment]
> Now, this process (with the templates in headers) must (eventually, maybe not this PR, but the sooner the better) be replicated for the remaining `*_app.cu` files:
> 
> ./bc/bc_app.cu,
> ./bfs/bfs_app.cu,
> ./color/color_app.cu,
> ./geo/geo_app.cu,
> ./gtc/gtc_app.cu,
> ./gtf/gtf_app.cu,
> ./hello/hello_app.cu,
> ./hits/hits_app.cu,
> ./knn/knn_app.cu,
> ./louvain/louvain_app.cu,
> ./mf/mf_app.cu,
> ./pr/pr_app.cu,
> ./proj/proj_app.cu,
> ./pr_nibble/pr_nibble_app.cu,
> ./rw/rw_app.cu,
> ./sage/sage_app.cu,
> ~./sm/sm_app.cu,~
> ./ss/ss_app.cu,
> ./sssp/sssp_app.cu,
> ./tc/tc_app.cu,
> ./vn/vn_app.cu,

Yes, after we merge this PR, we'll follow the same idea and make it consistent with other apps.

**Comment by neoblizz** [comment]
Is this good for a merge then?

**Comment by aschaffer** [comment]
It looks like this fix (branch) hasn't been merged into master, yet. I've just cloned gunrock and `sm_app.cuh` is not there. We will need it (soon) in order to expose fixed SM. Any plans?

**Comment by aschaffer** [comment]
Issue #2: We discovered that we have deeper dependencies on GRMAT than initially thought. Since, it seems that you kept (?) `grmat.cuh` around, is there a fast (one/two days programmer work) to revive it? Or, what would be the best way for us to extract the GRMAT dependencies out of gunrock and then append them to cugraph. 

I see the following dependencies that `cugraph/cpp/src/utilities/grmat.cu` has on gunrock:

gunrock/gunrock/coo.cuh
    #include <gunrock/util/basic_utils.h> // -- gone...
    #include <gunrock/util/error_utils.cuh>

gunrock/gunrock/util/memset_kernel.cuh // -- gone...
    #include <gunrock/coo.cuh>

gunrock/gunrock/csr.cuh
    #include <gunrock/util/test_utils.cuh>
    #include <gunrock/util/error_utils.cuh>
    #include <gunrock/util/multithread_utils.cuh>
    #include <gunrock/util/sort_omp.cuh>
    #include <gunrock/coo.cuh>

gunrock/gunrock/graphio/grmat.cuh
    #include <gunrock/util/memset_kernel.cuh> // -- gone...

cugraph/cpp/src/utilities/grmat.cu
    #include <gunrock/csr.cuh>
    #include <gunrock/graphio/grmat.cuh>

Where some of the files still there have changed. So, is there a quick way to revive GRMAT with acceptable / minimal disruption?

**Comment by neoblizz** [comment]
> Issue #1: It looks like this fix (branch) hasn't been merged into master, yet. I've just cloned gunrock and `sm_app.cuh` is not there. We will need it (soon) in order to expose fixed SM. Any plans?

I will do a minor release with the fixes. Should see it soon in master branch.

**Comment by neoblizz** [comment]
> Issue #2: We discovered that we have deeper dependencies on GRMAT than initially thought. Since it seems that you kept (?) `grmat.cuh` around, is there a fast (one/two days programmer work) to revive GRMAT functionality? Or, what would be the best way for us to extract the GRMAT dependencies out of gunrock and then append them to cugraph.
> 
> I see the following dependencies that `cugraph/cpp/src/utilities/grmat.cu` has on gunrock:
> 
> gunrock/gunrock/coo.cuh
> #include <gunrock/util/basic_utils.h> // -- gone...
> #include <gunrock/util/error_utils.cuh>
> 
> gunrock/gunrock/util/memset_kernel.cuh // -- gone...
> #include <gunrock/coo.cuh>
> 
> gunrock/gunrock/csr.cuh
> #include <gunrock/util/test_utils.cuh>
> #include <gunrock/util/error_utils.cuh>
> #include <gunrock/util/multithread_utils.cuh>
> #include <gunrock/util/sort_omp.cuh>
> #include <gunrock/coo.cuh>
> 
> gunrock/gunrock/graphio/grmat.cuh
> #include <gunrock/util/memset_kernel.cuh> // -- gone...
> 
> cugraph/cpp/src/utilities/grmat.cu
> #include <gunrock/csr.cuh>
> #include <gunrock/graphio/grmat.cuh>
> 
> Where some of the files still there have changed. So, is there a quick way to revive GRMAT with acceptable / minimal disruption?

Yes, let me try to wrap this up with the above mentioned minor release.

**Comment by aschaffer** [comment]
Thank you, @neoblizz

**Comment by aschaffer** [comment]
Also, from what I've seen GRMAT functionality is header-only, as far as the gunrock side is concerned (if I'm not mistaken). It would be great if we can keep it that way, so that we don't have a link dependency against Gunrock for GRMAT, only headers (there is a `grmat.cu` but _we_ maintain it). Thanks.

**Comment by neoblizz** [comment]
> Also, from what I've seen GRMAT functionality is header-only, as far as the gunrock side is concerned (if I'm not mistaken). It would be great if we can keep it that way, so that we don't have a link dependency against Gunrock for GRMAT, only headers (there is a `grmat.cu` but _we_ maintain it). Thanks.

I am guessing you'd only need `gunrock/gunrock/graphio/grmat.cuh` compatible with the v1.x.x API? The `.cu` app doesn't matter then? And also, do you only need a GPU version of RMAT generator with values (I know we have a few other things in there, but not sure to what extent do you need this support; COO format? MTX file? CSR format?)

**Comment by aschaffer** [comment]
We maintain a `grmat.cu`. I wasn't aware of any `*.cu` for GRMAT on Gunrock side (see above the list of dependencies that I'm aware of; as you can see the only `*.cu` file is our own `cugraph/cpp/src/utilities/grmat.cu`). 

Of course, I could be wrong. In which case we need to keep whatever GRMAT functionality was available in Gunrock `v0.5.1`, the latest before we decided to upgrade (which is _now_). So, if there were Gunrock `*.cu` files (i.e., other than our own) involved in GRMAT back in version `v0.5.1` then we still need them. COO, CSR, MTX (CSV if you have it): yes, we need them, as long as they are readily available. No time for new stuff in GRMAT.

**Comment by aschaffer** [comment]
So, it seems that `grmat.cuh` got "replaced" by `rmat.cuh` (wasn't really replaced as both files seem to coexist, but only the latter seems to be relevant). 

However, in the process some classes that we depend on got dropped. Like `Coo_nv`. Is there a replacement we should use instead (`CooSwitch`)? I'd rather not write `grmat.cu` from scratch, if possible.

**Comment by aschaffer** [comment]
Also, I'd like to emphasize that our code freeze is in one week. We probably need Gunrock in a stable release in a couple of days so that we have time to do the integration on our side.

**Comment by aschaffer** [comment]
@neoblizz, as a result of replacing `grmat.cuh` with `rmat.cuh` (`grmat.cuh` is still there, but cannot be included because it includes headers that don't exist anymore, like `memset_kernel.cuh`) a lot of functionality that we used to generate graphs has vanished.

Examples:
`struct Coo_nv`;
`void *BuildRmatGraph_coo(SizeT num_nodes, ...)`

What should we replace it with? It looks like our implementation of `gdf_grmat_gen(...)` the graph generator that uses Gunrock code and residing in `cugraph/cpp/src/utilities/grmat.cu` must be completely replaced. But with what? 

BTW, here's a list of files that seem to be dead code, since they also include now defunct `memset_kernel.cuh`:
```
$ find ./ -name "*.c*" -exec grep -nH "memset_kernel" '{}' \;
./gunrock/app/cc/cc_problem.cuh:18:#include <gunrock/util/memset_kernel.cuh>
./gunrock/app/dup/dup_partitioner.cuh:24:#include <gunrock/util/memset_kernel.cuh>
./gunrock/app/cp/cp_partitioner.cuh:23:#include <gunrock/util/memset_kernel.cuh>
./gunrock/app/sp/sp_partitioner.cuh:23:#include <gunrock/util/memset_kernel.cuh>
./gunrock/app/brp/brp_partitioner.cuh:23:#include <gunrock/util/memset_kernel.cuh>
./gunrock/app/rp/rp_partitioner.cuh:24:#include <gunrock/util/memset_kernel.cuh>
./gunrock/priority_queue/near_far_pile.cuh:19:#include <gunrock/util/memset_kernel.cuh>
./gunrock/util/kernel_runtime_stats.cuh:17://#include <gunrock/util/memset_kernel.cuh>
./gunrock/util/global_barrier.cuh:18:#include <gunrock/util/memset_kernel.cuh>
./gunrock/util/array_utils.cuh:25://#include <gunrock/util/memset_kernel.cuh>
./gunrock/graphio/grmat.cuh:17:#include <gunrock/util/memset_kernel.cuh>
(base) aschaffer$ find ./ -name "memset_kernel.cuh"
(base) aschaffer$
```

**Pull request merged**
