### PR TITLE
solution to git issue #454

### PR DESCRIPTION
**Pull request by DanLoran**
I have a a debug version of the changed csr.cuh file on my local machine that can be run in nsight debugger to confirm that my function works.

### CODE REVIEW

**Comment by porumbes** [comment]
Ditto on the binary search. The index information for CSR should be sorted by construction.

@neoblizz @sgpyc @yzhwang Do we have a good example of where this new method could/should be used? It would be nice for a certain level of testing. Either way, I think it would be good to have a little google test of this method (and eventually more).

**Comment by neoblizz** [comment]
> Ditto on the binary search. The index information for CSR should be sorted by construction.
> 
> @neoblizz @sgpyc @yzhwang Do we have a good example of where this new method could/should be used? It would be nice for a certain level of testing. Either way, I think it would be good to have a little google test of this method (and eventually more).

The reason, why I made that issue, was 1) due to the completion of the API and 2) SNN did this by hand, so (SNN or KNN) would be a great example to substitute this code into instead of hardcoding an implementation.

**Comment by DanLoran** [comment]
Committed requested function using BinarySearch. Had some issues using the BinarySearch_RightMost utility that similar functions (GetEdgeSrc, GetEdgeSrcDest) use, am looking into developing a googletest with @porumbes to pinpoint the issue. As it is, this commit currently works by using a different binary search utility.

**Comment by porumbes** [comment]
Looks good with the binary search, but please remove the commented out code.

**Pull request merged**
