### PR TITLE
Updated requirements for Gunrock version 0.3.

### PR DESCRIPTION
**Pull request by neoblizz**

### CODE REVIEW

**Comment by huanzhang12** [comment]
Please compile and use the latest Doxygen (1.8.11) and regenerate. Doxygen coming with Ubuntu 15.04 has a bug that 3-backtick code blocks are not rendered correctly. (Sorry I forgot to mention this yesterday). You can take a look at release_notes.html and see what happened.

**Comment by neoblizz** [comment]
Alright, I will push another commit with Doxygen 1.8.11.

**Comment by huanzhang12** [comment]
Thanks! Make sure you check every page is generated correctly before you commit.

**Comment by neoblizz** [comment]
@huanzhang12 How do I go about checking? Just open it in a browser and see if it is displayed correctly?

**Comment by huanzhang12** [comment]
Yes, just open the index.html inside directory "0.3" and navigate.

**Comment by neoblizz** [comment]
Looks good, I don't see any page that is messed up. Code blocks are showing properly too.

**Comment by huanzhang12** [comment]
Can you also squash your two commits into one? It does not make sense to include the wrong commit (generated by older doxygen), which will mess up the log and people cannot easily figure out what is going on. Thanks!

**Comment by huanzhang12** [comment]
Please also include a better commit message, describing what you changed in this commit.

**Comment by neoblizz** [comment]
Do not pull, still fixing it. Did an incorrect squash.

**Comment by neoblizz** [comment]
@huanzhang12 Looks good?

**Comment by huanzhang12** [comment]
Looks great! Merged. Thank you!

**Pull request merged**
